import React from 'react';
import borderLine from "../../Assets/Rectangle 3605.png";
import image from "../../Assets/Rectangle 3608.png";

function FeaturedCollections(props) {
  const collections = [
    { id:1,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    {id:2, image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:3,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:4,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:5,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:6,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:7,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:8,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:9,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
    { id:10,image: image, heading: "Women Round Neck Cotton Top", dec: "$149" },
  ];

 


  // Creating the list of product items using a for loop
  const productElements = [];
  for (let i = 0; i < props.productCount; i++) {
    const item = collections[i];
    productElements.push(
      <div key={i} className='flex flex-col space-y-1.5 text-gray-700 cursor-pointer transition ease-in-out hover:scale-105'>
        <img src={item.image} alt="img" className="w-2xs" />
        <h1 className='text-sm'>{item.heading}</h1>
        <h1 className='text-sm font-medium'>{item.dec}</h1>
      </div>
    );
  }

  return (
    <div className='mt-20 max-sm:px-[49px]'>
      <div className='flex flex-col items-center space-y-2'>
        <div className='flex items-center'>
          <h1 className='font bold text-3xl leading-10'>
            <span className="text-gray-500 font-medium">{props.title1} </span>
            <span className="text-gray-700 font-medium mr-2">{props.title2} </span>
          </h1>
          <img src={borderLine} alt="img" className='h-0.5 flex'></img>
        </div>
        {props.showIntro && (
          <p className='text-gray-600 max-sm:text-center max-sm:text-sm'>
            Lorem ipsum is simply dummy text of the printing and typesetting industry. Lorem ipsum has been the.
          </p>
        )}
      </div>

      <div className='mt-12 grid grid-cols-5 gap-x-4 gap-y-4  max-sm:grid-cols-2 max-sm:mx-4'style={{ marginLeft: '160px', marginRight: '160px' }}>

        {productElements}  {/* Render the products using the array generated by the for loop */}
      </div>
    </div>
  );
}

export default FeaturedCollections;
